### ISSUE TITLE
create healthcheck for coordinator

### ISSUE THREAD

**Issue by hugoArregui** [decentraland/world#95]
Required by the LB

**Comment by mgagliardo** [comment]
The healthcheck *should be* an HTTP call to the service, the port can be any you want, ideally healthchecks do some sort of "preflight" checks like check DB status, FS status or checking other services that should be up and running in order to run smoothly.

I've found [this MS guide](https://docs.microsoft.com/en-us/azure/architecture/patterns/health-endpoint-monitoring) to be very simple and helpful.

If it is too difficult to achieve this lets just start with a "return 200" and we'll eventually take care of it, just at least so we do not have to make a 404 look like a 200 on the Load Balancer.
